buildpack: nodejs-static
env_file: .env
nodejs:
  run_before_install:
    - |
      RUN apk --no-cache add git \
              shadow \
              gcc \
              musl-dev \
              autoconf \
              automake \
              make \
              libtool \
              nasm \
              tiff \
              jpeg \
              zlib \
              zlib-dev \
              file \
              pkgconf \
              util-linux
nginx:
  error_page:
    404: 404/
