type: node
env_file: .env
nodejs:
  env: web
  run:
    - |
      apk --no-cache add git \
          shadow \
          gcc \
          musl-dev \
          autoconf \
          automake \
          make \
          libtool \
          nasm \
          tiff \
          jpeg \
          zlib \
          zlib-dev \
          file \
          pkgconf \
          util-linux
    - yarn install --frozen-lockfile
    - yarn build
nginx:
  error_page:
    404: 404/
