name: Gatsby Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    env:
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gatsby build and deploy to gh-pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_SKIP_INDEXING: ${{ secrets.ALGOLIA_SKIP_INDEXING }}
          GOOGLE_ANALUTICS_ID: ${{ secrets.GOOGLE_ANALUTICS_ID }}
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: "--force"
          git_remote_url: "ssh://dokku@ixk.me/blog"
          ssh_private_key: ${{ secrets.DOKKU_PRIVATE_KEY }}
