name: Gatsby Deploy
on: [push, pull_request, repository_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: gatsby build and deploy to gh-pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_SKIP_INDEXING: ${{ secrets.ALGOLIA_SKIP_INDEXING }}
          LEANCLOUD_APP_ID: ${{ secrets.LEANCLOUD_APP_ID }}
          LEANCLOUD_APP_KEY: ${{ secrets.LEANCLOUD_APP_KEY }}
          LEANCLOUD_APP_URL: ${{ secrets.LEANCLOUD_APP_URL }}
          GOOGLE_ANALUTICS_ID: ${{ secrets.GOOGLE_ANALUTICS_ID }}
      - name: deploy to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: public
          remote: ${{ secrets.DEPLOY_REMOTE }}
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
