name: Gatsby Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    env:
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    container: quay.io/syfxlin/tilt
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes & Docker
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Setup secret env
        run: |
          echo "$SECRET_ENV" > .env
        env:
          SECRET_ENV: ${{ secrets.SECRET_ENV }}
      - name: Deploy to Kubernetes
        run: |
          tilt ci
